server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/music_db
    username: postgres
    password: #Вирішила не ділитися цією інформацією у GitHub=)
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: testLatticeApp

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
